### PR TITLE
fix(theme:default): fix inconsistency of top icon size

### PR DESCRIPTION
**Pull request by cipchk**
- close https://github.com/ng-alain/ng-alain/issues/2519

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-alain/delon/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by cipchk** [comment]
[Preview Preparing...](https://github.com/ng-alain/delon/actions/runs/11290538097)

**Comment by zengqinglei** [comment]
我检查了预览界面，大小仍然不一致；
同时我也查看了你们提交的源码，发现应该是针对这个是无效的，麻烦在确认下：
image

**Comment by cipchk** [comment]
针对这个 PR 的预览应该是 https://preview-1841-ng-alain-delon.surge.sh/dev/home

png:

QQ_1728919389512

**Comment by zengqinglei** [comment]
@cipchk 
Accepted, thank you!

**Pull request merged**
