### PR TITLE
docs: add en-US doc files for from widgets and third pary widgets

### PR DESCRIPTION
**Pull request by its404**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-alain/delon/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by cipchk** [comment]
@its404 有冲突，麻烦合并一下 `master` 分支，否则我无法合并。

**Comment by its404** [comment]
@cipchk , 已合并最新 `master`， 解决了冲突并增加了tree-select新增参数的英文翻译。

**Comment by cipchk** [comment]
@its404 如果条件允许，可以考虑对 Markdown Table 部分使用紧凑的风格，https://marketplace.visualstudio.com/items?itemName=cipchk.vscode-markdown-compact-table-formatter

**Comment by its404** [comment]
@cipchk , 好的，我稍后整体重新格式化一下。

**Comment by its404** [comment]
@cipchk , 已通过 `markdown compact table formatter` 格式化，谢谢！

**Pull request merged**
