### PR TITLE
Update basic.md

### PR DESCRIPTION
**Pull request by lenvaz**
While defining const, 

const chart: Chart = new (window as any).G2.Chart({
      container: el,
      autoFit: true,
      height: 500,
      width: el.clientWidth,
      padding: [20, 120, 95],
    });

Throws an error as follows:

core.js:5967 ERROR TypeError: Cannot read property 'Chart' of undefined.

Hence replaced it with the "Chart" Class import from g2 as below

import { Chart } from '@antv/g2';

const chart: Chart = new Chart({
      container: el,
      autoFit: true,
      height: 500,
      width: el.clientWidth,
      padding: [20, 120, 95],
    });

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ng-alain/delon/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by cipchk** [comment]
@lenvaz We use lazy loading G2 library in the latest version, so we will eventually use `window.G2` to instance.

**Comment by lenvaz** [comment]
Thanks for the acknowledgment,

**I am on the Ng-Alain version: "ng-alain": "^11.0.2"**

**The error i get is as below:**

**ERROR TypeError: Cannot read property 'Chart' of undefined**

How i used it in component:

import { Chart } from '@antv/g2';

this.chart = new (window as any).G2.Chart({
        container: el,
        autoFit: true,
        height: 500,
  }) as Chart;

**// Lazy Loading in routes module**
{ path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then((m) => m.DashboardModule) },


Imported the library in my lazy-loaded module as follows:

import { NgModule, Type } from '@angular/core';
import { SharedModule } from '@shared';
import { NzSkeletonModule } from 'ng-zorro-antd/skeleton';
import { DemoDelonChartModule } from 'src/app/delon.chart.module';
import { DashboardRoutingModule } from './dashboard-routing.module';
import { DashboardComponent } from './dashboard.component';

const COMPONENTS: Type<void>[] = [DashboardComponent];
const COMPONENTS_NOROUNT: Type<void>[] = [];

**// Concerned Module**

@NgModule({
  imports: [
    SharedModule,
    DemoDelonChartModule,
    NzSkeletonModule,
    DashboardRoutingModule
  ],
  declarations: [
    ...COMPONENTS,
    ...COMPONENTS_NOROUNT
  ],
})
export class DashboardModule { }


**// Charts Module**

import { NgModule } from '@angular/core';

// #region all modules

import { G2BarModule } from '@delon/chart/bar';
import { G2CustomModule } from '@delon/chart/custom';
import { G2PieModule } from '@delon/chart/pie';

const MODULES = [
    G2BarModule,
    G2CustomModule,
    G2PieModule,
];

// #endregion

@NgModule({ exports: MODULES })
export class DemoDelonChartModule { }



**Have i gone wrong somewhere? Please mention my mistake if you see it.**
**Thanks.**

**Comment by cipchk** [comment]
@lenvaz I suggest upgrading `@delon/*` to 11.1.0, and finally you can pass `(window as any).G2.Chart` initialize `G2`, full code like this:

```ts

    const chart: Chart = new (window as any).G2.Chart({
      container: el,
      autoFit: true,
      height: 500,
      width: el.clientWidth,
      padding: [20, 120, 95],
    });
```

This has the advantage that Angular will not package the G2 class library into `main.js` when building, it will first obtain the class library from the external CDN.

Abort document pls refer to [G2 class library loading](https://ng-alain.com/chart/getting-started/en#G2classlibraryloading).

**Comment by lenvaz** [comment]
Hi,

@cipchk thanks for the directions.
I have updated the theme and did the corresponding changes in the angular.json & global config file.
Yet i was facing an error as shown below.

util.js:402 GET http://localhost:4200/assets/@antv/g2/g2.min.js net::ERR_ABORTED 404 (Not Found)

util.js:402 GET http://localhost:4200/assets/@antv/data-set/data-set.js net::ERR_ABORTED 404 (Not Found)

With the following config in angular.json file (As mentioned in the latest documentation)

```
"assets": [
              // "src/favicon.ico",
              // "src/assets",
              {
                "glob": "**/*",
                "input": "src/assets/",
                "output": "/assets/"
              },
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@antv/g2/dist",
                "output": "/@antv/g2/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@antv/data-set/dist",
                "output": "/@antv/data-set/"
              }
            ]
```

And following in global-config.module.ts

```
const alainConfig: AlainConfig = {
 ... (this is just to show only charts config)
  chart: {
    libs: [
      './assets/@antv/g2/g2.min.js',
      './assets/@antv/data-set/data-set.js',
    ],
  }
};
```


Hence with the below change, I was able to fix the issue.


```
"assets": [
              {
                "glob": "**/*",
                "input": "src/assets/",
                "output": "/assets/"
              },
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@antv/g2/dist",
                "output": "/assets/@antv/g2/"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/@antv/data-set/dist",
                "output": "/assets/@antv/data-set/"
              }
            ]
```

Closing the pull request with this comment but please do the correction as mentioned above. If you think it's needed.

**Pull request closed without merging**
